English:
  ArmorNobleHelmet: Noble's Fur Hat
  ArmorNobleHelmet_description: A fur hat of the finest quality.
  ArmorNobleChest: Noble's Garb
  ArmorNobleChest_description: Chest armor fit for a noble. Stitched together from royal banners and reinforced with high quality materials.
  ArmorNobleLegs: Noble's Pants
  ArmorNobleLegs_description: Fine quality pants, strengthened by the best crafters in the land.
  ArmorNobleCape: Vegvisir Cape
  ArmorNobleCape_description: Cape fashioned from a vegvisir banner for the discerning adventurer.
  ArmorBarbarianBronzeHelmetJD: Barbarian's Helmet
  ArmorBarbarianBronzeHelmetJD_description: Helmet made to withstand the strongest blows.
  ArmorBarbarianBronzeChestJD: Barbarian's Armor
  ArmorBarbarianBronzeChestJD_description: Crafted to protect the bravest barbarians in the land.
  ArmorBarbarianBronzeLegsJD: Barbarian's Greaves
  ArmorBarbarianBronzeLegsJD_description: The thickest of hide, incredible metal alloys, and stitched to perfection.
  ArmorBarbarianCapeJD: Barbarian's Fur Cape
  ArmorBarbarianCapeJD_description: Cape made from rare lox pelt and designed to shelter the most fearless barbarian.
  ArmorWarriorHelmet: Warrior's Helmet
  ArmorWarriorHelmet_description: A strong helm that is fit for any warrior.
  ArmorWarriorChest: Warrior's Hauberk
  ArmorWarriorChest_description: The finest chainmail for the greatest of warriors.
  ArmorWarriorLegs: Warrior's Greaves
  ArmorWarriorLegs_description: Multi-layered greaves that keep the wearer warm and protected.
  ArmorPlateIronHelmetJD: Sturdy Plate Helmet
  ArmorPlateIronHelmetJD_description: A sturdy helmet made of the finest metal alloys.
  ArmorPlateIronChestJD: Sturdy Plate Mail
  ArmorPlateIronChestJD_description: Thick plates of metal alloy riveted to a leather harness.
  ArmorPlateIronLegsJD: Sturdy Plate Greaves
  ArmorPlateIronLegsJD_description: Sturdy greaves and knee guards that are reinforced with the strongest alloys.
  ArmorPlateCape: Warrior's Cape
  ArmorPlateCape_description: Reinforced with the finest lox pelts and worn around one's shoulders like a trophy.
  ArmorDragonslayerHelmet: Dragon Helm
  ArmorDragonslayerHelmet_description: Hatchlings tremble in fear when they see this scorched helmet adorned with the horns of their dragon queen.
  ArmorDragonslayerChest: Dragon Armor
  ArmorDragonslayerChest_description: Forged from the strongest metal and reinforced with rare dragon tears.
  ArmorDragonslayerLegs: Dragon Greaves
  ArmorDragonslayerLegs_description: Only the tears of a fierce dragon queen could make the black metal in this armor so strong.
  ArmorWandererHelmet: Wanderer's Hat
  ArmorWandererHelmet_description: Don't let the appearance fool you. This headgear is incredibly strong and reliable.
  ArmorWandererChest: Wanderer's Coat
  ArmorWandererChest_description: Small metal plates constructed of the strongest alloys, woven flax, and crafted by the finest blacksmiths.
  ArmorWandererLegs: Wanderer's Pants
  ArmorWandererLegs_description: Woven flax and metal alloys that provide incredible protection and mobility.
  ArmorWandererCape: Wanderer's Cape
  ArmorWandererCape_description: A cape that is crafted from the finest materials found in the Plains and meant to keep any wanderer comfortable.
  ArmorBlackmetalgarbHelmet: Nomadic Helmet
  ArmorBlackmetalgarbHelmet_description: Black metal alloy helmet with colorful padding fit for a nomad.
  ArmorBlackmetalgarbChest: Nomadic Garb
  ArmorBlackmetalgarbChest_description: A nomadic garb adorned with protective elements made from black metal alloy, most ofen found in the Plains.
  ArmorBlackmetalgarbLegs: Nomadic Greaves
  ArmorBlackmetalgarbLegs_description: Thick lox leather pants with black metal alloy guards stitched perfectly to protect the wandering nomad.
  ArmorSerpentHelmet: Serpent Helm
  ArmorSerpentHelmet_description: A thick black metal casque, reinforced with scales and adorned by the fins of a mighty sea serpent.
  ArmorSerpentChest_description: Plates of black metal overtop a surcoat made of lox pelt and sea serpent scales.
  ArmorSerpentLegs: Serpent Cuisses
  ArmorSerpentLegs_description: Black metal and serpent scales overlapping perfectly, to protect your thighs and lower legs.
  ArmorSerpentCape: Serpent Cape
  ArmorSerpentCape_description: A thick cape crafted by the best tailors on the coast. Guaranteed to keep any warrior warm on those long sea hunts.
  ArmorMistlandsHelmet: Scorched Helmet
  ArmorMistlandsHelmet_description: Helmet made from two rare metals and forged to perfection.
  ArmorMistlandsChest: Scorched Armor
  ArmorMistlandsChest_description: Flame metal layered into black metal to create a truly impressive armor.
  ArmorMistlandsLegs: Scorched Greaves
  ArmorMistlandsLegs_description: The scorched glow of this leg armor reminds you of distant lands to the south.
  BackpackSimple: Explorer Backpack
  BackpackSimple_description: A medium weight pack constructed of easily found materials. Great choice for any Viking expedition.
  BackpackHeavy: Marauder Backpack
  BackpackHeavy_description: A heavy duty pack constructed of quality materials. The truly adventurous Huskarl will opt for this excellent pack.
