- prefab: Deer
  biome: Meadows, BlackForest
  spawnChance: 50
  maxSpawned: 4
  spawnInterval: 100
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 64
  groupSizeMax: 3
  groupRadius: 5
  outsideForest: false
- prefab: Boar
  biome: Meadows
  spawnChance: 50
  maxSpawned: 4
  spawnInterval: 150
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 64
  groupSizeMax: 3
  groupRadius: 5
  levelUpMinCenterDistance: 800
- prefab: Neck
  biome: Meadows
  spawnChance: 50
  maxSpawned: 6
  spawnInterval: 100
  maxLevel: 3
  minAltitude: -1.5
  maxAltitude: 0.5
  spawnDistance: 5
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 5
  maxOceanDepth: 1
  levelUpMinCenterDistance: 800
- prefab: Neck
  biome: Meadows
  maxSpawned: 8
  spawnInterval: 30
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 10
  requiredEnvironments: Rain, ThunderStorm, LightRain
  spawnDistance: 32
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 5
  levelUpMinCenterDistance: 800
- prefab: Seagal
  biome: Meadows, BlackForest, Plains, Ocean
  spawnChance: 50
  maxSpawned: 5
  spawnInterval: 120
  minAltitude: -4
  maxAltitude: 0.2
  spawnDistance: 51
  groupSizeMax: 2
  groupRadius: 2
- prefab: Fish1
  biome: Meadows, BlackForest, Plains
  spawnChance: 50
  maxSpawned: 5
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -3
  maxAltitude: -1.5
  spawnDistance: 20
  groupSizeMin: 2
  groupSizeMax: 6
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish2
  biome: Meadows, BlackForest, Plains
  spawnChance: 50
  maxSpawned: 4
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -5
  maxAltitude: -2
  spawnDistance: 20
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish3
  biome: Ocean
  spawnChance: 50
  maxSpawned: 3
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 20
  groupSizeMax: 2
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish5
  biome: BlackForest
  spawnChance: 50
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 12
  groupSizeMin: 3
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish6
  biome: Swamp
  spawnChance: 60
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish7
  biome: Plains
  spawnChance: 60
  maxSpawned: 7
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 20
  groupSizeMin: 3
  groupSizeMax: 6
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish8
  biome: Ocean
  spawnChance: 50
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 12
  groupSizeMin: 2
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish9
  biome: Mistlands
  spawnChance: 50
  maxSpawned: 5
  spawnInterval: 60
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 12
  groupSizeMin: 2
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish12
  biome: Ocean, Mistlands
  spawnChance: 40
  maxSpawned: 8
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -6
  spawnDistance: 12
  groupSizeMin: 2
  groupSizeMax: 5
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish10
  biome: DeepNorth
  spawnChance: 60
  maxSpawned: 10
  spawnInterval: 70
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 12
  groupSizeMin: 3
  groupSizeMax: 10
  groupRadius: 3
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 15
- prefab: Fish11
  biome: AshLands
  spawnChance: 60
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 8
  groupSizeMin: 3
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 15
- prefab: Greydwarf
  biome: BlackForest
  spawnChance: 30
  maxSpawned: 3
  spawnInterval: 120
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtNight: false
  spawnDistance: 10
  groupSizeMin: 2
  groupSizeMax: 3
  groupRadius: 3
- prefab: Greydwarf
  biome: Meadows
  spawnChance: 30
  maxSpawned: 1
  spawnInterval: 120
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_eikthyr
  spawnDistance: 10
  groupSizeMin: 2
  groupSizeMax: 3
  groupRadius: 3
  outsideForest: false
- prefab: Greydwarf
  biome: BlackForest
  maxSpawned: 6
  spawnInterval: 60
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 4
  groupRadius: 10
- prefab: Greydwarf_Elite
  biome: BlackForest
  spawnChance: 50.6
  maxSpawned: 1
  spawnInterval: 120
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 10
  groupRadius: 1
  levelUpMinCenterDistance: 2000
- prefab: Fenring
  biome: Mountain
  biomeArea: median
  spawnChance: 20
  maxSpawned: 2
  spawnInterval: 400
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 10
  groupRadius: 1
- prefab: Greydwarf_Elite
  biome: Meadows
  spawnChance: 50.6
  maxSpawned: 1
  spawnInterval: 120
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_gdking
  spawnDistance: 10
  groupRadius: 1
- prefab: Greydwarf_Shaman
  biome: Meadows
  spawnChance: 50.6
  maxSpawned: 1
  spawnInterval: 120
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_gdking
  spawnDistance: 10
  groupRadius: 1
- prefab: Skeleton
  biome: Meadows, Swamp, Mountain, BlackForest, Plains
  spawnChance: 25
  maxSpawned: 3
  spawnInterval: 300
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_bonemass
  spawnDistance: 10
  groupSizeMax: 3
  groupRadius: 3
- prefab: Draugr
  biome: Meadows, Mountain, BlackForest, Plains
  spawnChance: 5
  maxSpawned: 1
  spawnInterval: 300
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_gdking
  requiredEnvironments: Misty
  spawnDistance: 10
  groupRadius: 1
- prefab: Goblin
  biome: Meadows, Mountain, BlackForest
  spawnChance: 5
  maxSpawned: 3
  spawnInterval: 3000
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_goblinking
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 3
  groupRadius: 3
  huntPlayer: true
- prefab: Seeker
  biome: Meadows, Mountain, BlackForest, Plains
  spawnChance: 5
  maxSpawned: 2
  spawnInterval: 3000
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_queen
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 3
  groupRadius: 3
  huntPlayer: true
- prefab: SeekerBrood
  biome: Meadows, Mountain, BlackForest, Plains
  spawnChance: 5
  maxSpawned: 5
  spawnInterval: 3000
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_queen
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 3
  groupRadius: 3
  huntPlayer: true
- prefab: Tick
  biome: Meadows, Mountain, BlackForest, Plains
  spawnChance: 5
  maxSpawned: 4
  spawnInterval: 3000
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_queen
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 3
  groupRadius: 3
  huntPlayer: true
- prefab: Greydwarf_Shaman
  biome: BlackForest
  spawnChance: 50.6
  maxSpawned: 2
  spawnInterval: 60
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 10
  groupRadius: 1
- prefab: Greydwarf
  biome: Meadows
  spawnChance: 50
  maxSpawned: 2
  spawnInterval: 200
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_eikthyr
  spawnDistance: 20
  groupRadius: 3
- prefab: Greyling
  biome: Meadows
  spawnChance: 50
  maxSpawned: 2
  spawnInterval: 300
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 30
  groupRadius: 3
  outsideForest: false
- prefab: odin
  biome: Meadows, Swamp, BlackForest, Plains
  spawnChance: 10
  maxSpawned: 1
  spawnInterval: 3000
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_gdking
  spawnDistance: 10
  spawnRadiusMin: 35
  spawnRadiusMax: 35
  groupRadius: 3
- prefab: Troll
  biome: BlackForest
  spawnChance: 5
  maxSpawned: 1
  spawnInterval: 4000
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 10
  groupRadius: 3
  levelUpMinCenterDistance: 2000
- prefab: Draugr
  biome: Swamp
  spawnChance: 50
  maxSpawned: 4
  spawnInterval: 120
  maxLevel: 3
  minAltitude: -1.5
  maxAltitude: 10
  spawnDistance: 10
  groupSizeMax: 2
  groupRadius: 3
- prefab: Skeleton
  biome: Swamp
  spawnChance: 25
  maxSpawned: 4
  spawnInterval: 400
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 10
  spawnDistance: 15
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 4
- prefab: Draugr_Elite
  biome: Swamp
  biomeArea: median
  spawnChance: 5
  maxSpawned: 1
  spawnInterval: 300
  minAltitude: -1.5
  maxAltitude: 10
  spawnAtDay: false
  spawnDistance: 15
  groupRadius: 1
- prefab: Surtling
  enabled: false
  biome: Swamp
  spawnChance: 30
  maxSpawned: 2
  spawnInterval: 40
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 30
  groupSizeMax: 2
  groupRadius: 1
- prefab: Blob
  biome: Swamp
  spawnChance: 20
  maxSpawned: 2
  spawnInterval: 500
  minAltitude: -1
  maxAltitude: 1000
  spawnDistance: 20
  groupSizeMax: 2
  groupRadius: 1
- prefab: Leech
  biome: Swamp
  spawnChance: 50
  maxSpawned: 10
  spawnInterval: 200
  maxLevel: 3
  minAltitude: -3
  maxAltitude: -0.1
  spawnDistance: 5
  groupRadius: 2
- prefab: BlobElite
  biome: Swamp
  spawnChance: 20
  maxSpawned: 1
  spawnInterval: 120
  minAltitude: -1
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 20
  groupRadius: 1
- prefab: Goblin
  biome: Plains
  spawnChance: 33
  maxSpawned: 5
  spawnInterval: 60
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 30
  groupSizeMin: 3
  groupSizeMax: 5
  groupRadius: 3
- prefab: Goblin
  biome: Plains
  spawnChance: 33
  maxSpawned: 2
  spawnInterval: 1000
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtNight: false
  spawnDistance: 30
  groupSizeMax: 2
  groupRadius: 3
- prefab: GoblinBrute
  biome: Plains
  spawnChance: 20
  maxSpawned: 1
  spawnInterval: 1000
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnAtNight: false
  spawnDistance: 100
  groupSizeMax: 2
  groupRadius: 3
- prefab: Lox
  biome: Plains
  spawnChance: 5
  maxSpawned: 3
  spawnInterval: 1000
  minAltitude: 1
  maxAltitude: 1000
  spawnDistance: 100
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 10
- prefab: Deathsquito
  biome: Plains
  spawnChance: 20
  maxSpawned: 3
  spawnInterval: 500
  minAltitude: 1
  maxAltitude: 1000
  spawnDistance: 30
  groupSizeMax: 2
  groupRadius: 10
  maxTilt: 99
  groundOffset: 1
- prefab: Wraith
  biome: Swamp
  spawnChance: 30
  maxSpawned: 2
  spawnInterval: 200
  minAltitude: -2
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 20
  groupRadius: 1
  groundOffset: 50
- prefab: StoneGolem
  biome: Mountain
  biomeArea: median
  spawnChance: 25.6
  maxSpawned: 1
  spawnInterval: 120
  minAltitude: 120
  maxAltitude: 1000
  spawnDistance: 10
  groupRadius: 4
- prefab: Hatchling
  biome: Mountain
  biomeArea: median
  spawnChance: 25.6
  maxSpawned: 2
  spawnInterval: 120
  minAltitude: 100
  maxAltitude: 1000
  spawnDistance: 10
  groupRadius: 4
  maxTilt: 66
  groundOffset: 10
- prefab: Wolf
  biome: Mountain
  biomeArea: median
  spawnChance: 50
  maxSpawned: 6
  spawnInterval: 120
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 30
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 5
  maxTilt: 45
- prefab: Wolf
  biome: Mountain
  biomeArea: median
  spawnChance: 25.6
  maxSpawned: 3
  spawnInterval: 400
  minAltitude: 0
  maxAltitude: 1000
  spawnAtNight: false
  spawnDistance: 30
  groupSizeMax: 2
  groupRadius: 5
  maxTilt: 45
- prefab: FireFlies
  biome: BlackForest
  maxSpawned: 4
  spawnInterval: 20
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 10
  groupRadius: 3
- prefab: Surtling
  biome: AshLands
  maxSpawned: 10
  spawnInterval: 8
  minAltitude: -1000
  maxAltitude: 1000
  spawnDistance: 10
  groupRadius: 3
- prefab: Serpent
  biome: Ocean
  biomeArea: median
  spawnChance: 5
  maxSpawned: 1
  spawnInterval: 1000
  minAltitude: -1000
  maxAltitude: -5
  spawnAtDay: false
  spawnDistance: 50
  groupRadius: 3
- prefab: Serpent
  biome: Ocean
  biomeArea: median
  spawnChance: 5
  maxSpawned: 1
  spawnInterval: 1000
  minAltitude: -1000
  maxAltitude: -5
  requiredEnvironments: ThunderStorm, Rain
  spawnDistance: 50
  groupRadius: 3
- prefab: Abomination
  biome: Swamp
  biomeArea: median
  spawnChance: 35
  maxSpawned: 1
  spawnInterval: 4000
  maxLevel: 0
  minAltitude: -2
  maxAltitude: 5
  spawnDistance: 30
  groupRadius: 1
  groundOffset: 0
- prefab: Seeker
  biome: Mistlands
  biomeArea: median
  spawnChance: 30
  maxSpawned: 2
  spawnInterval: 200
  maxLevel: 2
  minAltitude: 0
  maxAltitude: 1000
  spawnAtNight: false
  spawnDistance: 30
  groupSizeMin: 2
  groupSizeMax: 3
  groupRadius: 6
- prefab: Dverger
  biome: Mistlands
  biomeArea: median
  spawnChance: 30
  maxSpawned: 2
  spawnInterval: 1000
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtNight: false
  spawnDistance: 30
  groupSizeMax: 2
  groupRadius: 3
- prefab: Seeker
  biome: Mistlands
  biomeArea: median
  spawnChance: 20
  maxSpawned: 6
  spawnInterval: 300
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 40
  groupSizeMin: 2
  groupSizeMax: 3
  groupRadius: 6
- prefab: Gjall
  biome: Mistlands
  biomeArea: median
  spawnChance: 10
  maxSpawned: 1
  spawnInterval: 4000
  maxLevel: 0
  minLevel: 0
  minAltitude: 0
  maxAltitude: 1000
  spawnAtNight: false
  spawnDistance: 50
  groupRadius: 1
  maxTilt: 90
  groundOffset: 6
- prefab: Gjall
  biome: Mistlands
  biomeArea: median
  spawnChance: 10
  maxSpawned: 1
  spawnInterval: 4000
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 50
  groupRadius: 1
  maxTilt: 90
  groundOffset: 6
- prefab: Hare
  biome: Mistlands
  spawnChance: 50
  maxSpawned: 10
  spawnInterval: 100
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 10
  groupSizeMax: 3
  groupRadius: 6
- prefab: SeekerBrute
  biome: Mistlands
  biomeArea: median
  spawnChance: 10
  maxSpawned: 1
  spawnInterval: 4000
  maxLevel: 3
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 40
  groupRadius: 12
